In [1]:


import numpy as np
import pandas as pd

# Read the CSV file
df = pd.read_csv(r'C:\Users\NARASAREDDY\OneDrive\Desktop\Overian_cancer_prediction\data\synthetic.csv')

# Display the column names to verify what columns exist
print("Available columns:", df.columns.tolist())

# Only drop SUBJECT_ID if it exists
if 'SUBJECT_ID' in df.columns:
    df = df.drop('SUBJECT_ID', axis=1)

Available columns: ['age', 'CA125', 'HE4', 'CA19-9', 'AFP', 'GGT', 'CEA', 'HGB', 'ALP', 'CA72-4', 'Ca', 'menopausal_status', 'family_history', 'smoking_status', 'alcohol', 'cancer']

In [9]:
# Display column names and first few rows
print("Column names:")
print(df.columns.tolist())
print("\nFirst few rows:")
print(df.head())

Column names:
['age', 'CA125', 'HE4', 'CA19-9', 'AFP', 'GGT', 'CEA', 'HGB', 'ALP', 'CA72-4', 'Ca', 'menopausal_status', 'family_history', 'smoking_status', 'alcohol', 'cancer']

First few rows:
   age       CA125         HE4     CA19-9         AFP         GGT        CEA  \
0   52   31.940448   54.636526  27.951179    6.067196   35.071353   3.190016
1   57   26.308792   29.600789  19.134563    3.699989   39.631195   3.920936
2   46    8.157548   48.663123  23.296249    8.634846   15.291518   4.887950
3   61  374.972490  338.121306  69.109853  215.492236  172.240959  16.670379
4   69   10.558178   26.881335  31.612782    7.489990   20.892616   0.587509

         HGB         ALP    CA72-4         Ca menopausal_status  \
0  13.514886   79.835541  5.918484   9.744894               yes
1  14.053141   95.035055  1.227026   9.074549               yes
2  13.330515  119.592674  5.469088   8.876579               yes
3  11.043405  137.544481  6.325774  10.096846               yes
4  12.007993  112.868081  3.489533   9.406916               yes

  family_history smoking_status alcohol  cancer
0             no             no     yes       0
1            yes             no      no       0
2             no             no     yes       0
3             no            yes      no       1
4            yes            yes     yes       0

In [10]:
# Map the cancer status column (update the column name based on the actual name in your dataset)
# The column might be named 'Cancer', 'Status', or something similar
# Example: if the column is named 'Cancer_Status'
cancer_column = [col for col in df.columns if 'cancer' in col.lower() or 'status' in col.lower()][0]
df['has_cancer'] = df[cancer_column].map({'No': 0, 'Yes': 1})
print(f"Mapped values from column: {cancer_column}")
df

Mapped values from column: menopausal_status

,age,CA125,HE4,CA19-9,AFP,GGT,CEA,HGB,ALP,CA72-4,Ca,menopausal_status,family_history,smoking_status,alcohol,cancer,has_cancer
0,52,31.940448,54.636526,27.951179,6.067196,35.071353,3.190016,13.514886,79.835541,5.918484,9.744894,yes,no,no,yes,0,NaN
1,57,26.308792,29.600789,19.134563,3.699989,39.631195,3.920936,14.053141,95.035055,1.227026,9.074549,yes,yes,no,no,0,NaN
2,46,8.157548,48.663123,23.296249,8.634846,15.291518,4.887950,13.330515,119.592674,5.469088,8.876579,yes,no,no,yes,0,NaN
3,61,374.972490,338.121306,69.109853,215.492236,172.240959,16.670379,11.043405,137.544481,6.325774,10.096846,yes,no,yes,no,1,NaN
4,69,10.558178,26.881335,31.612782,7.489990,20.892616,0.587509,12.007993,112.868081,3.489533,9.406916,yes,yes,yes,yes,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,68,325.818567,223.915144,71.905009,267.853509,150.905449,16.950221,9.001872,224.974820,13.576190,10.498491,yes,no,yes,yes,1,NaN
996,62,24.992491,60.729010,1.595728,5.739504,44.139227,1.990775,12.209534,101.613602,2.014720,8.505396,yes,yes,yes,yes,0,NaN
997,57,27.281906,53.701950,35.989484,2.858414,12.844428,1.728285,13.973178,69.430049,4.906731,9.433855,yes,yes,yes,yes,0,NaN
998,69,13.338518,50.362916,12.438118,2.902837,31.647522,0.118582,11.319156,67.617259,5.657476,9.726570,yes,yes,yes,no,0,NaN
999,49,3.463902,18.996698,31.639049,3.464693,48.921814,4.898672,12.073104,33.688040,4.230380,9.266677,yes,yes,yes,yes,0,NaN

In [11]:
# Display value counts for has_cancer column
print("Distribution of has_cancer values:")
print(df['has_cancer'].value_counts())

Distribution of has_cancer values:
Series([], Name: count, dtype: int64)

In [12]:
# Display missing values count for each column
print("Missing values in each column:")
print(df.isnull().sum())

# Get all columns except 'has_cancer'
columns_to_fill = [col for col in df.columns if col != 'has_cancer']

# Replace missing values with mean for numeric columns
for column in columns_to_fill:
    if df[column].dtype != 'object':  # Only fill numeric columns
        df[column] = df[column].fillna(df[column].mean())

print("\nAfter filling missing values:")
print(df.isnull().sum())

Missing values in each column:
age                     0
CA125                   0
HE4                     0
CA19-9                  0
AFP                     0
GGT                     0
CEA                     0
HGB                     0
ALP                     0
CA72-4                  0
Ca                      0
menopausal_status       0
family_history          0
smoking_status          0
alcohol                 0
cancer                  0
has_cancer           1000
dtype: int64

After filling missing values:
age                     0
CA125                   0
HE4                     0
CA19-9                  0
AFP                     0
GGT                     0
CEA                     0
HGB                     0
ALP                     0
CA72-4                  0
Ca                      0
menopausal_status       0
family_history          0
smoking_status          0
alcohol                 0
cancer                  0
has_cancer           1000
dtype: int64

In [13]:
df.to_csv('ovarian_data.csv', index=False)

In [1]:
# Import required libraries
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
import numpy as np
import pickle

# Read the preprocessed dataset and check its content
df = pd.read_csv('ovarian_data.csv')
print("Step 1 - Initial DataFrame shape:", df.shape)

# Print column names and data types
print("\nColumns and their types:")
print(df.dtypes)

# Verify target variable exists and its content
if 'has_cancer' in df.columns:
    print("\nStep 2 - Unique values in target variable:")
    print(df['has_cancer'].value_counts(dropna=True))
else:
    raise ValueError("Target variable 'has_cancer' not found in the dataset")

# Handle missing values in target (if any)
df = df.dropna(subset=['has_cancer'])
print("\nStep 3 - Shape after removing rows with missing target:", df.shape)

# Identify columns by type
numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns
categorical_cols = df.select_dtypes(include=['object']).columns

print("\nNumeric columns:", len(numeric_cols))
print("Categorical columns:", len(categorical_cols))

# Fill numeric missing values with median
for col in numeric_cols:
    if col != 'has_cancer':
        median_val = df[col].median()
        df[col] = df[col].fillna(median_val)

# Fill categorical missing values with mode
for col in categorical_cols:
    if col != 'has_cancer':
        mode_val = df[col].mode().iloc[0] if not df[col].mode().empty else "Unknown"
        df[col] = df[col].fillna(mode_val)

print("\nStep 4 - Missing values after imputation:", df.isnull().sum().sum())

# Encode categorical variables
le_dict = {}
for col in categorical_cols:
    if col != 'has_cancer':
        le = LabelEncoder()
        df[col] = df[col].astype(str)
        df[col] = le.fit_transform(df[col])
        le_dict[col] = le

# Check data before numeric conversion
print("\nStep 5 - Unique values in has_cancer before conversion:")
print(df['has_cancer'].value_counts())

# Ensure target is numeric
if df['has_cancer'].dtype == 'object':
    print("\nConverting has_cancer to numeric")
    df['has_cancer'] = pd.to_numeric(df['has_cancer'], errors='coerce')

# Check data after numeric conversion
print("\nStep 6 - Unique values in has_cancer after conversion:")
print(df['has_cancer'].value_counts())

# Drop any remaining problematic rows
df = df.dropna()
print("\nStep 7 - Final shape before split:", df.shape)

# Additional check for empty dataset
if df.shape[0] == 0:
    raise ValueError("Dataset is empty after preprocessing. Check the previous steps for data loss.")

# Split features and target
X = df.drop('has_cancer', axis=1)
y = df['has_cancer']

print("\nStep 8 - Features shape:", X.shape)
print("Step 8 - Target shape:", y.shape)

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Train model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# Make predictions and evaluate
y_pred = rf_model.predict(X_test)

# Print model evaluation metrics
print("\nModel Evaluation:")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Plot confusion matrix
plt.figure(figsize=(8, 6))
sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.show()

# Feature importance plot
feature_importance = pd.DataFrame({
    'feature': X.columns,
    'importance': rf_model.feature_importances_
}).sort_values('importance', ascending=False)

plt.figure(figsize=(12, 6))
sns.barplot(x='importance', y='feature', data=feature_importance.head(10))
plt.title('Top 10 Most Important Features')
plt.show()

# Save the label encoders for later use
le_filename = 'label_encoders.pkl'
with open(le_filename, 'wb') as file:
    pickle.dump(le_dict, file)

NameError: name 'pd' is not defined

In [15]:
df

,AFP,AG,Age,ALB,ALP,ALT,AST,BASO#,BASO%,BUN,...,PCT,PDW,PHOS,PLT,RBC,RDW,TBIL,TP,UA,has_cancer
0,3.58,19.36,47,45.40,56.00,11.00,24.00,0.01,0.30,5.35,...,0.09,13.40,1.46,74.00,2.64,13.70,5.50,73.90,396.40,0
1,34.24,23.98,61,39.90,95.00,9.00,13.00,0.02,0.30,3.21,...,0.30,11.20,1.09,304.00,4.89,12.70,6.80,72.00,119.20,0
2,1.50,18.40,39,45.40,77.00,9.00,18.00,0.03,0.60,3.80,...,0.13,15.20,0.97,112.00,4.62,12.00,14.80,77.90,209.20,0
3,2.75,16.60,45,39.20,26.00,16.00,17.00,0.05,0.74,5.27,...,0.25,17.40,1.25,339.00,4.01,14.60,10.90,66.10,215.60,0
4,2.36,19.97,45,35.00,47.00,21.00,27.00,0.01,0.10,4.89,...,0.28,11.90,0.94,272.00,4.40,13.40,5.30,66.50,206.00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1344,7.22,13.80,79,38.86,89.90,17.56,16.50,0.05,0.48,19.92,...,0.11,9.71,1.24,415.74,5.22,12.64,1.19,62.89,5.33,0
1345,0.87,15.75,80,40.49,79.72,37.79,12.68,0.03,0.38,9.47,...,0.23,10.88,0.87,228.06,4.75,14.72,0.66,77.31,5.53,0
1346,0.34,14.96,32,36.87,86.87,10.27,16.31,0.06,0.05,19.14,...,0.21,13.11,0.72,380.62,4.62,12.45,0.70,71.56,2.98,0
1347,9.68,7.95,24,49.34,91.03,38.94,39.08,0.03,0.31,17.74,...,0.18,11.12,0.90,342.79,4.62,11.68,0.88,72.29,3.81,0
1348,4.66,8.57,38,37.46,68.72,34.55,33.38,0.04,0.44,11.63,...,0.17,11.90,0.74,279.16,5.68,13.87,0.67,76.17,4.32,0

In [17]:
# Define custom patient data
custom_data = {
    'AFP': [400.0],      # Provided: 400 ng/mL
    'AG': [18.5],        # Default value
    'Age': [65],         # Provided: 65
    'ALB': [42.0],       # Default value
    'ALP': [150.0],      # Provided: 150 U/L
    'ALT': [15.0],       # Default value
    'AST': [20.0],       # Default value
    'BASO#': [0.02],     # Default value
    'BASO%': [0.4],      # Default value
    'BUN': [5.0],        # Default value
    'Ca': [2.2],         # Provided: 2.2
    'CA125': [550.0],    # Provided: 550 U/mL
    'CA19-9': [60.0],    # Provided: 60 U/mL
    'CA72-4': [95.0],    # Provided: 95 U/mL
    'CEA': [20.0],       # Provided: 20 ng/mL
    'CL': [102.0],       # Default value
    'CO2CP': [24.0],     # Default value
    'CREA': [75.0],      # Default value
    'DBIL': [3.0],       # Default value
    'EO#': [0.05],       # Default value
    'EO%': [1.0],        # Default value
    'GGT': [180.0],      # Provided: 180 U/L
    'GLO': [30.0],       # Default value
    'GLU.': [5.0],       # Default value
    'HCT': [0.4],        # Default value
    'HE4': [420.0],      # Provided: 420 pmol/L
    'HGB': [120.0],      # Provided: 120
    'IBIL': [5.0],       # Default value
    'K': [4.5],          # Default value
    'LYM#': [1.5],       # Default value
    'LYM%': [25.0],      # Default value
    'MCH': [30.0],       # Default value
    'MCV': [90.0],       # Default value
    'Menopause': [1],    # Provided: 1
    'Mg': [1.0],         # Default value
    'MONO#': [0.3],      # Default value
    'MONO%': [5.0],      # Default value
    'MPV': [10.0],       # Default value
    'Na': [140.0],       # Default value
    'NEU': [65.0],       # Default value
    'PCT': [0.2],        # Default value
    'PDW': [12.0],       # Default value
    'PHOS': [1.2],       # Default value
    'PLT': [250.0],      # Default value
    'RBC': [4.5],        # Default value
    'RDW': [13.0],       # Default value
    'TBIL': [8.0],       # Default value
    'TP': [70.0],        # Default value
    'UA': [200.0]        # Default value
}

# Convert to DataFrame
custom_df = pd.DataFrame(custom_data)

# Make prediction
prediction = rf_model.predict(custom_df)
prediction_proba = rf_model.predict_proba(custom_df)

print("Prediction (0: No Cancer, 1: Cancer):", prediction[0])
print("\nProbability of each class:")
print("No Cancer: {:.2f}%".format(prediction_proba[0][0] * 100))
print("Cancer: {:.2f}%".format(prediction_proba[0][1] * 100))

Prediction (0: No Cancer, 1: Cancer): 0

Probability of each class:
No Cancer: 73.00%
Cancer: 27.00%

In [18]:
# Save the trained model using pickle
import pickle

# Save the model
model_filename = 'ovarian_cancer_model.pkl'
with open(model_filename, 'wb') as file:
    pickle.dump(rf_model, file)

# Save the LabelEncoder
encoder_filename = 'label_encoder.pkl'
with open(encoder_filename, 'wb') as file:
    pickle.dump(le, file)

print(f"Model saved as '{model_filename}'")
print(f"Label Encoder saved as '{encoder_filename}'")

# Example of how to load and use the model
print("\nExample of loading and using the saved model:")
with open(model_filename, 'rb') as file:
    loaded_model = pickle.load(file)
    
# Test if loaded model gives same prediction as original model
test_prediction = loaded_model.predict(custom_df)
print("Prediction from loaded model:", test_prediction[0])

Model saved as 'ovarian_cancer_model.pkl'
Label Encoder saved as 'label_encoder.pkl'

Example of loading and using the saved model:
Prediction from loaded model: 0